=== nuno407/terraform-provider-aws/healthcheck/healthcheck/schema/jsonschema/algorithm-output.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/bosch-rc-dev/container_scripts/healthcheck/schema/jsonschema/algorithm-output.json",
    "title": "Algorithm Output",
    "description": "Inference processing output metadata",
    "type": "object",
    "properties": {
        "_id": {
            "type": "string",
            "description": "Media recording ID"
        },
        "algorithm_id": {
            "type": "string",
            "description": "Processing algorithm ID"
        },
        "pipeline_id": {
            "type": "string",
            "description": "Pipeline execution ID"
        },
        "output_paths": {
            "type": "object",
            "description": "Algorithm output"
        },
        "if": {
            "properties": {
                "algorithm_id": {
                    "const": "CHC"
                }
            }
        },
        "then": {
            "properties": {
                "results": {
                    "type": "object",
                    "properties": {
                        "CHBs": {
                            "type": "array"
                        },
                        "CHBs_sync": {
                            "type": "object"
                        },
                        "CHC_periods": {
                            "type": "array"
                        }
                    }
                }
            }
        },
        "else": {
            "if": {
                "algorithm_id": {
                    "const": "Anonymize"
                }
            },
            "then": {
                "properties": {
                    "output_paths": {
                        "type": "object",
                        "properties": {
                            "metadata": {
                                "type": "string"
                            },
                            "video": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "required": [
        "_id",
        "algorithm_id",
        "pipeline_id",
        "output_paths"
    ]
}

=== nuno407/terraform-provider-aws/Metadata/tests/integration/test_data/algo_output.json
{
    "_id" : "srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645517710980_1645519350202_Anonymize",
    "algorithm_id" : "Anonymize",
    "pipeline_id" : "srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645517710980_1645519350202",
    "output_paths" : {
        "metadata" : "-",
        "video" : "qa-rcd-anonymized-video-files/Debug_Lync/srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645517710980_1645519350202_anonymized.mp4"
    }
}
