=== nuno407/terraform-provider-aws/healthcheck/healthcheck/schema/jsonschema/pipeline-execution.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/bosch-rc-dev/container_scripts/healthcheck/schema/jsonschema/pipeline-execution.json",
    "title": "Pipeline Execution",
    "description": "Pipeline execution status of a recording",

    "type": "object",
    "properties": {
        "_id": {
            "type": "string",
            "description": "Identifier for pipeline execution"
        },
        "data_status": {
            "type": "string",
            "description": "Execution status of the pipeline"
        },
        "from_container": {
            "description": "Microservice that persisted this status document",
            "type": "string"
        },
        "info_source": {
            "description": "Microservice that sent this status information",
            "type": "string"
        },
        "last_updated": {
            "type": "string",
            "description": "last time this status was updated"
        },
        "processing_list": {
            "type": "array",
            "description": "List of algorithms to be processed in this pipeline",
            "items": {
                "type": "string"
            }
        },
        "s3_path": {
            "type": "string"
        }
    },
    "required": [
        "_id",
        "data_status",
        "from_container",
        "info_source",
        "last_updated",
        "processing_list",
        "s3_path"
    ]
}

=== nuno407/terraform-provider-aws/Metadata/tests/integration/test_data/pipeline_executions.json
[
{
    "_id" : "srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645513203385_1645514871743",
    "data_status" : "complete",
    "from_container" : "Metadata",
    "info_source" : "SDM",
    "last_updated" : "2022-01-27T17:08:15.860010Z",
    "processing_list" : [ 
        "Anonymize", 
        "CHC"
    ],
    "s3_path" : "Debug_Lync/srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645513203385_1645514871743.mp4"
},
{
    "_id" : "srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645517710980_1645519350202",
    "data_status" : "complete",
    "from_container" : "Metadata",
    "info_source" : "SDM",
    "last_updated" : "2022-01-27T17:08:15.860010Z",
    "processing_list" : [ 
        "Anonymize", 
        "CHC"
    ],
    "s3_path" : "Debug_Lync/srxdriverpr1external07_rc_srx_qa_driverpr1_007_InteriorRecorder_1645517710980_1645519350202.mp4"
}
]

=== nuno407/terraform-provider-aws/healthcheck/tests/integration/data/mongo_data/test-pipeline-execution.json
[
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639067411688_1639067460000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-09T16:48:42.818394Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639067411688_1639067460000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639067580000_1639067640000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-09T16:53:51.186880Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639067580000_1639067640000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639126766137_1639126800000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-10T09:11:49.514927Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639126766137_1639126800000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639131720000_1639131780000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-10T10:39:12.161934Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639131720000_1639131780000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639315740000_1639315800000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-12T13:44:55.363826Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639315740000_1639315800000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639320898158_1639320900000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-12T15:01:13.097266Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639320898158_1639320900000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639320960000_1639321140000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-12T16:09:12.346358Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639320960000_1639321140000.mp4"
    },
    {
        "_id": "deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639321140000_1639321380000",
        "data_status": "complete",
        "from_container": "Metadata",
        "info_source": "CHC",
        "last_updated": "2021-12-12T16:27:43.106418Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_rc_srx_develop_ivs1hi_04_InteriorRecorder_1639321140000_1639321380000.mp4"
    },
    {
        "_id": "srxfut2internal01_rc_tst_qa_eur_fut2_001_InteriorRecorder_1643971450000_1643971472700+",
        "data_status": "received",
        "from_container": "Metadata",
        "info_source": "SDM",
        "last_updated": "2022-02-07T13:20:57.347832Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/srxfut2internal01_rc_tst_qa_eur_fut2_001_InteriorRecorder_1643971450000_1643971472700+.mp4"
    },
    {
        "_id": "deepsensation_ivs_slimscaley_develop_bic2hi_01_InteriorRecorder_1639750504360_1639750523828",
        "data_status": "received",
        "from_container": "Metadata",
        "info_source": "SDM",
        "last_updated": "2022-02-07T13:36:57.142624Z",
        "processing_list": [
            "Anonymize",
            "CHC"
        ],
        "s3_path": "Debug_Lync/deepsensation_ivs_slimscaley_develop_bic2hi_01_InteriorRecorder_1639750504360_1639750523828.mp4"
    }
]
